/**
 * Permission catalogue and the default role → permission matrix.
 * The matrix seeds the database; at runtime the DB (Role/Permission/RolePermission) is authoritative,
 * so a super admin can adjust roles without a deploy.
 */
export const PERMISSIONS = [
  "dashboard:read",
  "analytics:read",
  "product:read",
  "product:write",
  "product:delete",
  "category:write",
  "brand:write",
  "collection:write",
  "content:write",
  "inventory:read",
  "inventory:write",
  "order:read",
  "order:update",
  "order:cancel",
  "order:refund",
  "return:manage",
  "shipping:manage",
  "customer:read",
  "customer:write",
  "coupon:read",
  "coupon:write",
  "review:moderate",
  "support:read",
  "support:reply",
  "notification:manage",
  "audit:read",
  "settings:manage",
  "user:manage",
  "role:manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const SYSTEM_ROLES = [
  "customer",
  "support_agent",
  "inventory_manager",
  "order_manager",
  "product_manager",
  "manager",
  "admin",
  "super_admin",
] as const;
export type RoleKey = (typeof SYSTEM_ROLES)[number];

export const ROLE_DEFINITIONS: Record<RoleKey, { name: string; description: string; isStaff: boolean; permissions: readonly Permission[] }> = {
  customer: {
    name: "Customer",
    description: "Storefront shopper. Customer-scoped endpoints only — no admin permissions.",
    isStaff: false,
    permissions: [],
  },
  support_agent: {
    name: "Support Agent",
    description: "Handles customer tickets and can look up orders and customers.",
    isStaff: true,
    permissions: ["order:read", "customer:read", "support:read", "support:reply", "review:moderate"],
  },
  inventory_manager: {
    name: "Inventory Manager",
    description: "Manages stock levels, restocks and low-stock monitoring.",
    isStaff: true,
    permissions: ["dashboard:read", "product:read", "inventory:read", "inventory:write"],
  },
  order_manager: {
    name: "Order Manager",
    description: "Processes orders, shipments, returns and refunds.",
    isStaff: true,
    permissions: [
      "dashboard:read",
      "order:read",
      "order:update",
      "order:cancel",
      "order:refund",
      "return:manage",
      "shipping:manage",
      "customer:read",
      "inventory:read",
      "support:read",
    ],
  },
  product_manager: {
    name: "Product Manager",
    description: "Owns the catalogue: products, categories, brands, media, content and review moderation.",
    isStaff: true,
    permissions: [
      "dashboard:read",
      "product:read",
      "product:write",
      "product:delete",
      "category:write",
      "brand:write",
      "collection:write",
      "content:write",
      "inventory:read",
      "coupon:read",
      "review:moderate",
    ],
  },
  manager: {
    name: "Store Manager",
    description: "Runs day-to-day operations across catalogue, orders, customers and promotions.",
    isStaff: true,
    permissions: [
      "dashboard:read",
      "analytics:read",
      "product:read",
      "product:write",
      "product:delete",
      "category:write",
      "brand:write",
      "collection:write",
      "content:write",
      "inventory:read",
      "inventory:write",
      "order:read",
      "order:update",
      "order:cancel",
      "order:refund",
      "return:manage",
      "shipping:manage",
      "customer:read",
      "customer:write",
      "coupon:read",
      "coupon:write",
      "review:moderate",
      "support:read",
      "support:reply",
      "notification:manage",
      "audit:read",
    ],
  },
  admin: {
    name: "Administrator",
    description: "Full operational access, including staff accounts and store settings (not role editing).",
    isStaff: true,
    permissions: PERMISSIONS.filter((p) => p !== "role:manage"),
  },
  super_admin: {
    name: "Super Administrator",
    description: "Unrestricted access, including role and permission management.",
    isStaff: true,
    permissions: PERMISSIONS,
  },
};

export const isPermission = (v: string): v is Permission => (PERMISSIONS as readonly string[]).includes(v);
